web:
  build: frontend
  ports:
  - "80:3000"
  volumes:
  - ./frontend:/usr/src/app/:rw
  environment:
  - NODE_ENV=dev
  command: >
    sh -c '
      if test -d node_modules; 
      then 
        echo node_modules_exists ; 
      else 
        cp -a /tmp/node_modules /usr/src/app;
      fi && 
      npm install && 
      /usr/local/bin/node ./index.js
    '